# Generated by Django 2.1.7 on 2019-03-01 17:22

import card.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_detail',
            fields=[
                ('roll_no', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('father_name', models.CharField(max_length=256)),
                ('dob', models.DateField()),
                ('programme', models.CharField(max_length=256)),
                ('blood_group', models.CharField(max_length=256)),
                ('issued_on', models.DateField()),
                ('valid_upto', models.DateField()),
                ('pic', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
        migrations.CreateModel(
            name='Employee_Card',
            fields=[
                ('e_id', models.CharField(default=card.models.id_gen, editable=False, max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('designation', models.CharField(max_length=256)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=256)),
                ('pic', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('valid_upto', models.DateField()),
                ('issued_on', models.DateField(null=True)),
            ],
        ),
    ]
